version: "2.1"
services:
  api:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - .:/usr/src
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/bucketlist_dev
  frontend:
    image: frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_BASE_URL=http://0.0.0.0:5000
      - REACT_APP_API_URI=http://0.0.0.0:5000/api/v1/
    links:
      - api
  database:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bucketlist_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "psql -h 'localhost' -U 'postgres' -c '\\l'"]
      interval: 30s
      timeout: 30s
      retries: 3